[package]
name = "beluga"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
tempfile = "3.20.0"

anyhow = "1.0.98"
notify = "6.1.1"
tiny_http = "0.12.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.104"
